# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
  - nightly
addons:
  apt:
    sources:
    - sourceline: 'deb [trusted=yes] https://apt.repos.intel.com/mkl all main'
      key_url: 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB'
    update: true
    packages:
    - gcc
    - intel-mkl-64bit-2019.5-075
before_script:
  - if [ `getconf LONG_BIT` = "64" ];then source /opt/intel/mkl/bin/mklvars.sh intel64; else source /opt/intel/mkl/bin/mklvars.sh ia32; fi
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - stage: Documentation
      julia: 1.1
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          Pkg.build();
          include("docs/make.jl");'
      after_success: skip
